### ISSUE TITLE
Mock JNI calls

### ISSUE THREAD

**Issue by strazzere** [rednaga/native-shim#1]
Much like mocking for testing, we should be able to mock specific JNI methods so that the target process can call then and get faked data which might be needed. This will also allow us to feed targets specific data and quickly catch any data they are passing outside of their contexts.

**Comment by Kompwu** [comment]
@strazzere Hi, How's going ?

**Comment by CalebFenton** [comment]
A good way to get attention is with a PR :D

**Comment by Kompwu** [comment]
@CalebFenton I'm not sure how i can do it.
I'm gonna make a mess :sweat_smile:

**Comment by strazzere** [comment]
I didn't even realize I had this issue open.

It's actually all set/ready since @CalebFenton added the initialization of the VM and I added some code for it to work on Art.

Ex: https://github.com/rednaga/native-shim/blob/master/shim.c#L66

If you still want to "mock" or "hook" things, you could do a simple function patch so that it gets called directly by the child process - or just have the host process call them directly.

**Comment by khaledalweshah** [comment]
Can you fix it to work with android 10.

**Comment by strazzere** [comment]
This works fine on 10, you'll need to make a new issue with a better description from your last one. Since everything you described in the last one was not relevant to any issue with the code.

Closing this issue as it is old and attracting unwanted comments.
