### ISSUE TITLE
Not being able to use FindClass JNI method for third party libs on Android Pie

### ISSUE THREAD

**Issue by perks** [rednaga/native-shim#3]
Not sure if this is the right place, but it looks like this project is a little more actively maintained. Referencing the issue here https://github.com/CalebFenton/native-harness-target/issues/3, basically wondering if it is possible in latest Android versions to use the JNI `FindClass` method with the VM shim to load third party libraries.

**Comment by CalebFenton** [comment]
I'm not familiar with any recent Android changes. Are you trying to build a Dalvik VM, set it up a certain way, and then pass it to a native library function?

The code you posted on the issue you linked will only work if you bother to create that class and make it available to the VM, but it's not clear what your setup is. Could you post some more details on what you're trying to do?

**Comment by perks** [comment]
Hi @CalebFenton thanks for replying so quickly. Am actually following along https://calebfenton.github.io/2017/04/14/calling_jni_functions_with_java_object_arguments_from_the_command_line/ using your code found here (invoking `harness` after downstreaming the Android 7 ART changes fails at the snippet in the link) where you are having the VM instantiate the test target application class because you are invoking the native decryption function via its Java-land method instance.

Maybe I missed something reading it, but invoking the `FindClass` function within the harness doesn't seem to pick up the application's library

Edit: the particular fail case is here:
```
  printf(" [+] Finding Cryptor class\n");
  jclass cryptor_class;
  cryptor_class = (*env)->FindClass(env, "org.cf.nativeharness.Cryptor");
  if (cryptor_class == NULL) {
    printf(" [!] Couldn't find Cryptor on the class path\n");
    return -1;
  } else {
    printf(" [+] Found Cryptor class: %p\n", cryptor_class);
  }
```

**Comment by CalebFenton** [comment]
Why do you think the `org.cf.nativeharness.Cryptor` class is available to the VM?

Specifically, did you do something like: `adb push lib/x86/libstr-crypt.so /data/local/tmp`?

How are you running harness?

Are you running from `/data/local/tmp`? If not, you'll have to modify `opt[2].optionString = "-Djava.library.path=/data/local/tmp";`

Is your emulator x86?

**Comment by perks** [comment]
I've tried it on Android 8 and 9 both on hardware and x86 emulator. I am running from `/data/local/tmp` with the library pushed over. So i've tried also tried with the `-debug` apks vs signing the unsigned `release` ones and using them (in case there was some weird thing that might happen with adding packages to class path?) but same results in either case.

Here is some output using `aarch64` targets to help clarify:

```bash
walleye:/data/local/tmp # pm list packages | grep native
package:org.cf.nativeharness
walleye:/data/local/tmp # /data/local/tmp/harness /data/local/tmp/libstr-crypt.so
[*] Native Harness
 [+] Loading target: [ /data/local/tmp/libstr-crypt.so ]
 [+] Library Loaded!
 [+] Found JNI_OnLoad, good
 [+] Initializing JavaVM Instance
 [+] Initialization success (vm=0x6c1c2fe400, env=0x6c1c2e0380)
 [+] Calling JNI_OnLoad
 [+] Found decryptString function, good (0x6c1898669c)
 [+] Finding Cryptor class
 [!] Couldn't find Cryptor on the class path
255|walleye:/data/local/tmp #
```

**Comment by CalebFenton** [comment]
I see. I'm just trying to eliminate all the obvious stuff. What about `/data/local/tmp/target-app.apk`? Does it exist? Does it contain the Crypto class?

**Comment by perks** [comment]
```
walleye:/data/local/tmp # ls -l app-arm8-debug.apk
-rw-rw-rw- 1 shell shell 1516455 2018-12-03 15:10 app-arm8-debug.apk
```
Running the app through a launcher invokes the string correctly in the GUI (installed via `adb install` so the `apk` file in `/data/local/tmp/` was just pushed there).

The `apk` just contained the `classes.dex` bytecode, afaik there isn't any place where Java class files can be found inside an APK?

**Comment by CalebFenton** [comment]
So to confirm, `/data/local/tmp` contains `app-target.apk`? This is necessary because of this line: `opt[0].optionString = "-Djava.class.path=/data/local/tmp/target-app.apk";`.

This option says "classes are available at this location", and if that apk is missing, classes will fail to load.

Yes, the apk contains classes.dex and that's dalvik bytecode, and you're right, there are no Java class files inside the apk, but we're dealing with dalvikvm, so it's looking for dalvik classes. If you built target-app correctly, and you're sure, then checking isn't that useful. If you're not totally sure, you can use baksmali on target-app.apk and confirm the Cryptor class is there.

**Comment by perks** [comment]
Ah modifying the `opt[0]` string worked -- I was accidentally messing with `opt[2]` when doing tests. Thanks so much for all your patience and help! Your work on Dalvik/smali tooling is really educational and insightful.

**Comment by strazzere** [comment]
Glad you both had been able to solve this!

**Comment by CalebFenton** [comment]
Good luck in your quest.
