### ISSUE TITLE
creating JVM hangs on Android API 28 (v9)

### ISSUE THREAD

**Issue by evandrix** [rednaga/native-shim#4]
https://github.com/rednaga/native-shim/blob/master/vm.c#L12 should be `opt[4].optionString = "-Xno_sig_chain";`

**Comment by CalebFenton** [comment]
Why?

**Comment by CalebFenton** [comment]
Actually, any extra detail at all would be helpful here.

**Comment by evandrix** [comment]
`-Xno-sig-chain` is not a recognized switch, while `-Xno_sig_chain` is

**Comment by CalebFenton** [comment]
Thanks @evandrix!

**Comment by CunningLogic** [comment]
I need a copy of hosd_signed from firmware.zip but needs to match the phone
variant, eg Sprint att Verizon etc
