### ISSUE TITLE
Is it possible for this code to run directly in app native?

### ISSUE THREAD

**Issue by PhD-5** [rednaga/native-shim#5]
I had run shim code on my Nexus 6P successfully. And I tried to run vm.c/vm.h code in an App native (.so) instead of an independent executable. But it failed when creating a new another JVM.
Is it possible to create another JVM when one exists in current process already？

Thanks  : )

**Comment by CalebFenton** [comment]
I've never used it that way but it should be possible. It's not that
special.

How did it fail? What was the error? What did the android logs say?

**Comment by PhD-5** [comment]
JNI_CreateJavaVM(&(*p_vm), &(*p_env), &args) just return -1 without any logs.

**Comment by PhD-5** [comment]
https://android.googlesource.com/platform/dalvik.git/+/refs/tags/android-4.2.2_r1/vm/Jni.cpp#3469

I found a comment in JNI_CreateJavaVM  source code.
'''dvmFprintf(stderr, "ERROR: Dalvik only supports one VM per process\n");'''

Maybe process in android just supports ONE VM? VM is singleton?

**Comment by strazzere** [comment]
How are you attempting to run this? If you have an app already inside a DVM (which JNI calls JVM), you just pass it to it, like you would any shared library. You don't need to create a new one that is mostly fake.

**Comment by CalebFenton** [comment]
I'm skeptical that the android logs were completely silent about this failure. Maybe you're confusing stdout with android logs??? https://developer.android.com/studio/debug/am-logcat

I think @strazzere is right on this -- you're probably not using this how it's meant to be used.
