### ISSUE TITLE
Not working with Android 10. 

### ISSUE THREAD

**Issue by khaledalweshah** [rednaga/native-shim#7]
Can you make it to support android 10. 
Because in android 10 , when loading lib , it ask for another libs that's founded in another folder:
/apex/com.android.runetime/lib. 

It got an error on calling libart.so

**Comment by strazzere** [comment]
This doesn't really have anything to do with the code. You'll need to provide those libraries and pass them to the environment variable `LD_LIBRARY_PATH` like you would in any other case.

**Comment by ivanjx** [comment]
It seems that `JNI_CreateJavaVM` is moved to `libandroid_runtime.so` on Android 10+. Here is my current implementation:
```
    // Loading shared libraries.
    void *libandroid_runtime_dso = dlopen("libandroid_runtime.so", RTLD_NOW);

    if (!libandroid_runtime_dso) 
    {
        printf("Unable to load libandroid_runtime.\n");
        return -1;
    }

    void *libdvm_dso = dlopen("libdvm.so", RTLD_NOW);

    if (!libdvm_dso) 
    {
        libdvm_dso = dlopen("libart.so", RTLD_NOW);

        if (!libdvm_dso) 
        {
            // Android 10 uses libandroid_runtime.
            libdvm_dso = libandroid_runtime_dso;
        }
    }

    JNI_CreateJavaVM_t JNI_CreateJavaVM;
    JNI_CreateJavaVM = (JNI_CreateJavaVM_t) dlsym(libdvm_dso, "JNI_CreateJavaVM");
    
    if (!JNI_CreateJavaVM) 
    {
        printf("Unable to load createjavavm.\n");
        return -1;
    }
```

This code works until i want to call this:
```
    if (JNI_CreateJavaVM(&vm, (void **)&env, &args)) 
    {
        printf("Unable to create java vm.\n");
        return -1;
    }
````

The program crashed instead of printing unable to create java vm error and says:

![image](https://user-images.githubusercontent.com/12814796/98347600-2ed03d80-204a-11eb-84e6-3953f3c87bc9.png)

Any idea?
Thanks.

**Comment by strazzere** [comment]
You should create a new ticket for this, also, you need to post the core dump.

I'm unsure what you're running into on this without that data is it works for me?

**Comment by taoboyang** [comment]
> 

I have gotten the same problem. Have you solved this problem? Thanks
